### ISSUE TITLE
İnternet Çağrısı bölümündeki hata.

### ISSUE THREAD

**Issue by ghost** [ingbrzy/MA-XML-5.0-TURKISH#30]
Merhaba 

Rehber -> Ayarlar -> Diğer Telefon Ayarları ->  İnternet Çağrısı Ayarları

hesap ekle dediğimde crash olup kapanıyor ayrıca dili ingilizce yaptığımda sorunsuz çalışıyor. 

ingilizce olarak hesap eklediğimde dili tekrar türkçeye aldığımda çalışıyor gibi gözüküyor ama çağrı yapmıyor.

kullandığım telefonlar -> Nexus 4 -> Note 2  

ikisindede aynı. 

ilginize teşekkür ederim.
Çalışamalarınızda başarılar.

**Comment by ghost** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.phone/com.android.phone.sip.MiuiSipEditor}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2207)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
at android.app.ActivityThread.access$600(ActivityThread.java:142)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1235)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5070)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.android.phone.sip.SipEditor.loadPreferencesFromProfile(SipEditor.java:521)
at com.android.phone.sip.SipEditor.onCreate(SipEditor.java:203)
at com.android.phone.sip.MiuiSipEditor.onCreate(MiuiSipEditor.java:21)
at android.app.Activity.performCreate(Activity.java:5188)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
... 11 more
Samsung Note 2
LG Nexus 4

**Comment by ingbrzy** [comment]
when it happens..?

**Comment by ghost** [comment]
I got an error when I click on the internet call - add account.

**Comment by ingbrzy** [comment]
will be fixed in today's release...

**Comment by ingbrzy** [comment]
hmm.. still FC... looking into it deeper...
