### ISSUE TITLE
Calendar new event FC

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-5.0-TURKISH#32]
check arrays in calendar.apk...

java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
at java.util.ArrayList.remove(ArrayList.java:399)
at com.android.calendar.event.EventViewUtils.reduceMethodList(EventViewUtils.java:195)
at com.android.calendar.event.EditEventView.prepareAvailability(EditEventView.java:960)
at com.android.calendar.event.EditEventView.onItemSelected(EditEventView.java:1700)
at android.widget.AdapterView.fireOnSelected(AdapterView.java:892)
at android.widget.AdapterView.access$200(AdapterView.java:49)
at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:860)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4898)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ingbrzy** [comment]
if there is in the log java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2

it means you have in arrays just 2 options where should be more..

for example:

you have

   < string-array name="availability">
        <item>Meşgul</item>
        <item>Uygun</item>
    < /string-array>

should be

```
< string-array name="availability">
    <item>Busy</item>
    <item>Available</item>
<item>Tentative</item>
< /string-array>  
```

I saw more.. check it with mine please..

**Comment by cmadencan** [comment]
compared it with the sk arrays. t no diff..

< string-array name="availability" >
        <item>Zaneprázdnený</item >
        <item>Dostupný</item >
< item>Nezáväzný</item >

**Comment by cmadencan** [comment]
I'm going to the hospital ..I'm gonna check it this evening... thanks for help.

**Comment by ingbrzy** [comment]
dont worry.. fixed... https://github.com/ingbrzy/MA-XML-5.0-TURKISH/commit/27f1fc2e9b178976fa909a4f7d6beca9d9ce7eae

just translate it.. :+1:
